FROM node:24.11.1-slim

WORKDIR /home/app/

# install angular cli globally in the container
RUN npm i -g @angular/cli@20

# #############################################################################
# Start init script (install dependencies and start dev server)
# 
ENTRYPOINT ["/bin/bash", "/home/app/image/init.sh"]

## for project init
# CMD ["sh"]

